-- Migration 010: Add display_name column to documents
-- Human-readable Hebrew title for documents, generated by Document_Namer service.
-- Uses IF NOT EXISTS for idempotency.

ALTER TABLE documents ADD COLUMN IF NOT EXISTS display_name TEXT DEFAULT NULL;
